packages:
  - "."
  - "library"
allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  lefthook: true
  puppeteer: true
  sharp: true
  vue-demi: true
ignoreWorkspaceRootCheck: true
overrides:
  "@types/react": "$@types/react"
  "@types/react-dom": "$@types/react-dom"
  gsap: "$gsap"
  react: "$react"
  react-dom: "$react-dom"
