export const NEEDS = ["Branding", "Web Design", "Development", "SEO", "Content Strategy"]

export const INDUSTRIES = [
	{ label: "Technology", value: "technology" },
	{ label: "Healthcare", value: "healthcare" },
	{ label: "Finance", value: "finance" },
	{ label: "Education", value: "education" },
	{ label: "Retail", value: "retail" },
]

export const ROLES = ["Designer", "Developer", "Manager"]

export const COUNTRIES = [
	"Argentina",
	"Australia",
	"Austria",
	"Belgium",
	"Brazil",
	"Canada",
	"Chile",
	"China",
	"Colombia",
	"Czech Republic",
	"Denmark",
	"Egypt",
	"Finland",
	"France",
	"Germany",
	"Greece",
	"Hungary",
	"India",
	"Indonesia",
	"Ireland",
	"Israel",
	"Italy",
	"Japan",
	"Malaysia",
	"Mexico",
	"Netherlands",
	"New Zealand",
	"Nigeria",
	"Norway",
	"Pakistan",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Romania",
	"Saudi Arabia",
	"Singapore",
	"South Africa",
	"South Korea",
	"Spain",
	"Sweden",
	"Switzerland",
	"Thailand",
	"Turkey",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"United States",
	"Vietnam",
]

export const SKILLS = [
	"React",
	"Vue",
	"Angular",
	"Next.js",
	"TypeScript",
	"JavaScript",
	"Node.js",
	"Python",
	"Ruby",
	"Go",
	"Rust",
	"Java",
	"PHP",
	"GraphQL",
	"REST API",
	"Docker",
	"Kubernetes",
	"AWS",
	"GCP",
	"Azure",
	"PostgreSQL",
	"MySQL",
	"MongoDB",
	"Redis",
	"Figma",
	"Tailwind CSS",
]
