name: Lighthouse

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  library:
    # this hash is updated automatically, so if you're resolving a merge conflict, either hash is fine
    uses: reformcollective/library/.github/workflows/lighthouse.yml@7d448949601c1fced351b8468849edef9bc6ee71
    secrets:
      SECRETS_JSON: ${{ toJSON(secrets) }}
    with:
      runOnGithubActions: false
