name: Check For Updates
# run daily at noon MST
on:
  # TODO enable this when ready
  # schedule:
  #   - cron: "0 19 * * *"
  workflow_dispatch:
jobs:
  library:
    # this hash is updated automatically, so if you're resolving a merge conflict, either hash is fine
    uses: reformcollective/library/.github/workflows/check-updates.yml@22b03127c3b9ba4e8bd04f1a9cce6094a8a31b21
