name: Code Checks
on: pull_request
jobs:
  library:
    # this hash is updated automatically, so if you're resolving a merge conflict, either hash is fine
    uses: reformcollective/library/.github/workflows/code-checks.yml@a6a34ba90b2399ee1c5a44275d38bffd768c9613
    secrets:
      SECRETS_JSON: ${{ toJSON(secrets) }}
    with:
      runOnGithubActions: false
