name: Check For Updates
# run daily at noon MST
on:
  # TODO enable this when ready
  # schedule:
  #   - cron: "0 19 * * *"
  workflow_dispatch:
jobs:
  library:
    # this hash is updated automatically, so if you're resolving a merge conflict, either hash is fine
    uses: reformcollective/library/.github/workflows/check-updates.yml@4bd40445aee662199e62f9ae29ffe77fac45dccc
