name: Code Checks
on: pull_request
jobs:
  library:
    # this hash is updated automatically, so if you're resolving a merge conflict, either hash is fine
    uses: reformcollective/library/.github/workflows/code-checks.yml@6fedda1fbb260b4a3bcb26aebb69fb59474ec2ee
    secrets:
      SECRETS_JSON: ${{ toJSON(secrets) }}
    with:
      runOnGithubActions: false
