name: Check For Updates
# run daily at noon MST
on:
  # TODO enable this when ready
  # schedule:
  #   - cron: "0 19 * * *"
  workflow_dispatch:
jobs:
  library:
    uses: reformcollective/library/.github/workflows/check-updates.yml@af5d8edae8a48d954e9196cb3cc89e7a2d49f1d4
