name: Lighthouse

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  library:
    # this hash is updated automatically, so if you're resolving a merge conflict, either hash is fine
    uses: reformcollective/library/.github/workflows/lighthouse.yml@0751b94ec8f7c606b3a1dc7ed408072b45ff80ff
    secrets:
      SECRETS_JSON: ${{ toJSON(secrets) }}
    with:
      runOnGithubActions: false
